Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2018-07, with the labels that each got.

#399 Fix a small typo in spring-cloud-gateway.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#415 Document the order of the filterchain (#400)
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#294 Autoconfigure CloudFoundryRouteServiceRoutePredicateFactory and add cloudFoundryRouteService in DSL
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/PredicateSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CloudFoundryRouteServiceRoutePredicateFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: enhancement

#457 Fix bug where metrics fail if actuator is not added as a project depency
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/GatewaySampleApplication.java
  spring-cloud-gateway-sample/src/test/java/org/springframework/cloud/gateway/sample/GatewaySampleApplicationTests.java
  spring-cloud-gateway-sample/src/test/java/org/springframework/cloud/gateway/sample/GatewaySampleApplicationWithoutMetricsTests.java
Labels: bug

#439 Caches body object in ReadBodyPredicate
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/handler/predicate/ReadBodyPredicateFactory.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/ReadBodyPredicateFactoryTest.java
Labels: in progress
