Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-09, with the labels that each got.

#1292 I think there should not import classes in log4j #1290
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/ipresolver/XForwardedRemoteAddressResolver.java
Labels: in progress

#1295 Gh 1294 add reactive sc loadbalancer support
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayLoadBalancerClientAutoConfiguration.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayReactiveLoadBalancerClientAutoConfiguration.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/LoadBalancerClientFilter.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/ReactiveLoadBalancerClientFilter.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/DelegatingServiceInstance.java
  spring-cloud-gateway-core/src/main/resources/META-INF/spring.factories
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/ReactiveLoadBalancerClientFilterTests.java
  spring-cloud-starter-gateway/pom.xml
Labels: enhancement

#1284 FIX #1282 Rewrite filter example
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: waiting-for-triage

#1215 Fixes cache is cleared on refresh but not actually refreshed. Fixes gh-1168.
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/discovery/DiscoveryClientRouteDefinitionLocator.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/CachingRouteDefinitionLocator.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/CachingRouteDefinitionLocatorTests.java
Labels: in progress

#1212 relates to gh-600 Add Predicate and Filter validation to Route Creation Actuator Endpoint
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/actuate/AbstractGatewayControllerEndpoint.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/actuate/GatewayControllerEndpoint.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/actuate/GatewayLegacyControllerEndpoint.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/actuate/GatewayControllerEndpointTests.java
Labels: enhancement

#1311 Add PropertiesTagsProvider
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayMetricsAutoConfiguration.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayMetricsProperties.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/tagsprovider/PropertiesTagsProvider.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/support/tagsprovider/PropertiesTagsProviderTests.java
Labels: in progress
