Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-08, with the labels that each got.

#1223 #821 read timeout is not retried noconflict
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/RetryGatewayFilterFactory.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RetryGatewayFilterFactoryIntegrationTests.java
Labels: waiting-for-triage

#1230 In case the failureType coming from Hystrix is SHOSRTCIRCUIT, then HTTP 503 is dispatched
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/ServiceUnavailableException.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactoryTests.java
Labels: waiting-for-triage

#1247 Fix comment in RequestRateLimiterGatewayFilterFactory
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/RequestRateLimiterGatewayFilterFactory.java
Labels: documentation

#1246 Fix wrong indentation in the document.
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#1245 FIX the wrong description in doc for "RewritePath GatewayFilter Factory"
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#1251 clean duplicate logger in ServerWebExchangeUtils class
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/ServerWebExchangeUtils.java
Labels: bug
