Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-12, with the labels that each got.

#1452 Adding possible to override the RouteLocator
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
Labels: enhancement

#1468 Fixed Duplicate Host Header Issue
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/PreserveHostHeaderGatewayFilterFactoryTests.java
Labels: in progress

#1120 add possibility to override response and connect timeouts per route #…
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/RouteMetadataUtils.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/NettyRoutingFilterIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/builder/RouteBuilderTests.java
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: in progress

#1437 document SecureHeadersGatewayFilterFactory
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: in progress

#1456 Editing pass
  .gitignore
  docs/src/main/asciidoc/_attributes.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#1460 Fix CachingRouteLocator issue during routes initialization
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/CachingRouteLocator.java
Labels: bug

#1489 Remove routed attribute when executing fallbacks in circuit breakers
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/RetryGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/SpringCloudCircuitBreakerFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/ServerWebExchangeUtils.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/HystrixTestConfig.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/SpringCloudCircuitBreakerFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/SpringCloudCircuitBreakerTestConfig.java
Labels: in progress
