Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-02, with the labels that each got.

#797 remove lombok in doc
  README.adoc
  docs/src/main/asciidoc/README.adoc
Labels: documentation, waiting for feedback

#836 Revisited documentation about writing a custom global pre/post-filter
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: waiting-for-triage

#839 Fix documentation
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: waiting-for-triage

#849 Add new row to Grafana dashboard that includes four JVM panels
  docs/src/main/asciidoc/gateway-grafana-dashboard.json
Labels: documentation

#856 Make RedisRateLimiter omit headers if property is set
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiter.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiterTests.java
Labels: waiting-for-triage

#467 Handle partial encoded URI. #462
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/support/ServerWebExchangeUtils.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/RouteToRequestUrlFilterTests.java
Labels: in progress
