Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-03, with the labels that each got.

#824 light tests cleanup
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/test/BaseWebClientTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/test/ssl/SingleCertSSLTests.java
  spring-cloud-gateway-core/src/test/resources/application-logging.yml
  spring-cloud-gateway-core/src/test/resources/application-multi-cert-ssl.yml
  spring-cloud-gateway-core/src/test/resources/application-redis-rate-limiter-config.yml
  spring-cloud-gateway-core/src/test/resources/application-redis-rate-limiter-default-config.yml
  spring-cloud-gateway-core/src/test/resources/application-remote-address.yml
  spring-cloud-gateway-core/src/test/resources/application-removenonproxyheaders.yml
  spring-cloud-gateway-core/src/test/resources/application-request-header-web-filter.yml
  spring-cloud-gateway-core/src/test/resources/application-request-parameter-web-filter.yml
  spring-cloud-gateway-core/src/test/resources/application-save-session-web-filter.yml
  spring-cloud-gateway-core/src/test/resources/application-single-cert-ssl.yml
  spring-cloud-gateway-core/src/test/resources/application-weights-404.yml
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: enhancement

#860 HttpHeadersFilter for WebClientHttpRoutingFilter
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/WebClientHttpRoutingFilter.java
Labels: enhancement

#892 URL Cleanup
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
Labels: waiting-for-triage

#904 Fixed typos in doc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#911 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-fu/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#906 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#905 URL Cleanup
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
Labels: waiting-for-triage

#866 Dedupe response header filter
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/DedupeResponseHeaderGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/DedupeResponseHeaderGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/DedupeResponseHeaderGatewayFilterFactoryUnitTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/test/AdhocTestSuite.java
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: in progress

#926 Use raw path when passing path to PathContainer.parsePath
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/handler/predicate/PathRoutePredicateFactory.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/PathRoutePredicateFactoryTests.java
Labels: in progress

#935 URL Cleanup
  bootstrap/css/bootstrap-responsive.css
  bootstrap/css/bootstrap-responsive.min.css
  bootstrap/css/bootstrap.css
  bootstrap/css/bootstrap.min.css
  bootstrap/js/bootstrap.js
  bootstrap/js/bootstrap.min.js
Labels: waiting-for-triage

#929 URL Cleanup
  .settings.xml
  LICENSE.txt
  spring-cloud-gateway-mvc/src/main/java/org/springframework/cloud/gateway/mvc/ProxyExchange.java
  spring-cloud-gateway-mvc/src/main/java/org/springframework/cloud/gateway/mvc/config/ProxyExchangeArgumentResolver.java
  spring-cloud-gateway-mvc/src/main/java/org/springframework/cloud/gateway/mvc/config/ProxyProperties.java
  spring-cloud-gateway-mvc/src/main/java/org/springframework/cloud/gateway/mvc/config/ProxyResponseAutoConfiguration.java
  spring-cloud-gateway-mvc/src/test/java/org/springframework/cloud/gateway/mvc/ProductionConfigurationTests.java
  spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/GatewaySampleApplication.java
  spring-cloud-gateway-sample/src/test/java/org/springframework/cloud/gateway/sample/GatewaySampleApplicationTests.java
Labels: waiting-for-triage

#978 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CloudFoundryRouteServiceRoutePredicateFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CookieRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteDefinitionRouteLocatorTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#977 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/handler/predicate/RemoteAddrRoutePredicateFactory.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToWebFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#976 URL Cleanup
  1.0.x/index.html
  1.0.x/multi/multi_gateway-starter.html
  1.0.x/single/spring-cloud-gateway.html
  2.0.x/index.html
  2.0.x/multi/multi__configuration.html
  2.0.x/multi/multi__glossary.html
  2.0.x/multi/multi_gateway-request-predicates-factories.html
  2.0.x/multi/multi_gateway-route-filters.html
  2.0.x/multi/multi_gateway-starter.html
  2.0.x/single/spring-cloud-gateway.html
  2.1.x/index.html
  2.1.x/multi/multi__actuator_api.html
  2.1.x/multi/multi__configuration.html
  2.1.x/multi/multi__cors_configuration.html
  2.1.x/multi/multi__gatewayfilter_factories.html
  2.1.x/multi/multi__glossary.html
  2.1.x/multi/multi_gateway-request-predicates-factories.html
  2.1.x/multi/multi_gateway-starter.html
  2.1.x/single/spring-cloud-gateway.html
  Gemfile
  Gemfile.lock
  README.markdown
  _config.yml
  _includes/download_widget.md
  _sample-pages/project.html
  _sample-pages/project_group.html
  bootstrap/css/bootstrap-select.css
  bootstrap/js/bootstrap-select.js
  bootstrap/js/bootstrap.js
  css/main.css.css
  font-awesome/css/font-awesome-ie7.css
  font-awesome/css/font-awesome.css
  index.html
  js/backbone.js
  js/highlight/styles/dracula.min.css
  js/highlight/styles/monokai-sublime.min.css
  js/highlight/styles/monokai.min.css
  js/jquery.js
  js/test/SpecRunner.html
  js/test/lib/support/mock-ajax.js
  js/test/spec/QuickStartWidgetSpec.js
  js/underscore.js
  multi/multi__actuator_api.html
  multi/multi__configuration.html
  multi/multi__cors_configuration.html
  multi/multi__gatewayfilter_factories.html
  multi/multi__glossary.html
  multi/multi_gateway-request-predicates-factories.html
  multi/multi_gateway-route-filters.html
  multi/multi_gateway-starter.html
  single/spring-cloud-gateway.html
  spring-cloud-gateway.html
Labels: waiting-for-triage

#975 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#974 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CloudFoundryRouteServiceRoutePredicateFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CookieRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteDefinitionRouteLocatorTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#973 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CloudFoundryRouteServiceRoutePredicateFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CookieRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteDefinitionRouteLocatorTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#972 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/RequestHeaderToRequestUriGatewayFilterFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/BetweenRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CloudFoundryRouteServiceRoutePredicateFactoryIntegrationTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/handler/predicate/CookieRoutePredicateFactoryTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteDefinitionRouteLocatorTests.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/route/RouteTests.java
  spring-cloud-gateway-core/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
  spring-cloud-gateway-core/src/test/resources/application.yml
Labels: waiting-for-triage

#969 URL Cleanup
  README.adoc
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-sample/src/main/resources/application.yml
Labels: waiting-for-triage

#966 URL Cleanup
  .settings.xml
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#965 URL Cleanup
  .settings.xml
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#963 URL Cleanup
  .settings.xml
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-fn/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#962 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#961 URL Cleanup
  .settings.xml
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#960 URL Cleanup
  .settings.xml
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
Labels: waiting-for-triage

#959 URL Cleanup
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage

#958 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#957 URL Cleanup
  .settings.xml
Labels: waiting-for-triage

#925 URL Cleanup
  docs/pom.xml
  pom.xml
  spring-cloud-gateway-core/pom.xml
  spring-cloud-gateway-dependencies/pom.xml
  spring-cloud-gateway-mvc/pom.xml
  spring-cloud-gateway-rsocket/pom.xml
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-webflux/pom.xml
  spring-cloud-starter-gateway/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage
