Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-06, with the labels that each got.

#1043 Allow creation of HystrixCommandKey on basis of request context
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/HystrixGatewayFilterFactory.java
Labels: waiting-for-triage

#1044 Override the uri method with URI as its parameter
  spring-cloud-gateway-mvc/src/main/java/org/springframework/cloud/gateway/mvc/ProxyExchange.java
Labels: enhancement

#1042 Fixes gh-878 - secure headers can be disabled #1041
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/SecureHeadersGatewayFilterFactory.java
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/factory/SecureHeadersProperties.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/factory/SecureHeadersGatewayFilterFactoryUnitTests.java
Labels: in progress

#1093 Add methods using custom spec to GatewayFilterSpec::modifyResponseBody() and GatewayFilterSpec::modifyRequestBody()
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
Labels: waiting-for-triage

#1113 Fix wrong defaultValue in metadata
  spring-cloud-gateway-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: documentation
