Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2019-01, with the labels that each got.

#722 Allow isSecure property of LoadBalancer ServiceInstance to determine the scheme of the URL
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/LoadBalancerClientFilter.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/LoadBalancerClientFilterTests.java
  spring-cloud-gateway-core/src/test/resources/application-multi-cert-ssl.yml
  spring-cloud-gateway-core/src/test/resources/application-single-cert-ssl.yml
Labels: in progress

#737 Fixed type in documentation related to custom filters
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#741 refactor null safety http method resolving for non standard method
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java
Labels: bug

#786 Validate that we actually have a hostname when using a load balanced URI
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/filter/RouteToRequestUrlFilter.java
  spring-cloud-gateway-core/src/test/java/org/springframework/cloud/gateway/filter/RouteToRequestUrlFilterTests.java
Labels: in progress

#788 Add logging for routes loaded by gateway properties
  spring-cloud-gateway-core/src/main/java/org/springframework/cloud/gateway/config/GatewayProperties.java
Labels: enhancement
