Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2021-11, with the labels that each got.

#2426 Use LoadBalancer per-client properties.
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayReactiveLoadBalancerClientAutoConfiguration.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/LoadBalancerServiceInstanceCookieFilter.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/ReactiveLoadBalancerClientFilter.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/LoadBalancerServiceInstanceCookieFilterTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/ReactiveLoadBalancerClientFilterTests.java
Labels: enhancement

#2420 Disable per route response timeout with negative number
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/NettyRoutingFilterCompatibleTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/NettyRoutingFilterIntegrationTests.java
  spring-cloud-gateway-server/src/test/resources/application-netty-routing-filter.yml
  spring-cloud-gateway-server/src/test/resources/application.yml
Labels: in progress

#2440 New profile to skip Docker tests
  pom.xml
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/config/GatewayRedisRouteDefinitionRepositoryEnabledByPropertyTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiterTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/route/RedisRouteDefinitionRepositoryTests.java
Labels: task

#2446 Update _configprops.adoc
  docs/src/main/asciidoc/_configprops.adoc
Labels: documentation
