Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2021-03, with the labels that each got.

#2167 Fix getter/setter to match the variable name for FallbackHeaders
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/FallbackHeadersGatewayFilterFactory.java
Labels: task

#2173 Support passing selected ServiceInstance id downstream via cookie.
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayReactiveLoadBalancerClientAutoConfiguration.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/LoadBalancerServiceInstanceCookieFilter.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/config/conditional/DisableBuiltInGlobalFiltersTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/LoadBalancerServiceInstanceCookieFilterTests.java
Labels: enhancement

#2144 Fixes rewrite path example and discovery
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/discovery/GatewayDiscoveryClientAutoConfiguration.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/discovery/DiscoveryClientRouteDefinitionLocatorTests.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/discovery/GatewayDiscoveryClientAutoConfigurationTest.java
Labels: enhancement

#2142 feature-2140 `org.springframework.cloud.gateway.config.HttpClientProperties#proxy` consider specifying the proxy type?
  docs/src/main/asciidoc/_configprops.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/HttpClientProperties.java
Labels: in progress

#2179 Update Grafana dashboard to use new metric prefix
  docs/src/main/asciidoc/gateway-grafana-dashboard.json
  docs/src/main/asciidoc/images/gateway-grafana-dashboard.jpeg
Labels: bug
