Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2023-12, with the labels that each got.

#3158 (4.0.x) Refactor GRPC integration tests maven version configuration
  spring-cloud-gateway-integration-tests/grpc/pom.xml
Labels: dependencies

#3157 (main) Fix GRPC dependencies for GRPCApplicationTests
  spring-cloud-gateway-integration-tests/grpc/pom.xml
Labels: dependencies

#3126 Support query parameters in RedirectTo filter
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactory.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/factory/RedirectToGatewayFilterFactoryTests.java
  spring-cloud-gateway-server/src/test/resources/application.yml
Labels: enhancement, in progress

#3163 (4.0.x) Enhance "/actuator/gateway" endpoint
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/AbstractGatewayControllerEndpoint.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/GatewayControllerEndpoint.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/GatewayEndpointInfo.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/actuate/GatewayLegacyControllerEndpoint.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/actuate/GatewayControllerEndpointTests.java
Labels: enhancement
