Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2023-01, with the labels that each got.

#2825 Enable kotlin route DSL
  spring-cloud-gateway-sample/pom.xml
  spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/AdditionalRoutesImportSelector.java
  spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/GatewaySampleApplication.java
  spring-cloud-gateway-sample/src/test/java/org/springframework/cloud/gateway/sample/GatewaySampleApplicationTests.java
  spring-cloud-gateway-server/pom.xml
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/test/AdhocTestSuite.java
  spring-cloud-gateway-server/src/test/kotlin/org/springframework/cloud/gateway/route/builder/RouteDslTests.kt
Labels: in progress

#2539 Remove code quality image in README.adoc
  README.adoc
Labels: in progress

#2554 Fix properties in spring.cloud.gateway.filter.secure-headers documentation
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#2654 Fix typo
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/support/ServerWebExchangeUtils.java
Labels: documentation

#2664 Remove unnecessary reverse
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/support/ipresolver/XForwardedRemoteAddressResolver.java
Labels: task

#2308 Add @ConditionalOnMissingBean to FilteringWebHandler bean definition in autoconfiguration
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
Labels: enhancement

#2843 Fix docs for LocalResponseCache Filter
  docs/src/main/asciidoc/spring-cloud-gateway.adoc
Labels: documentation

#2844 Add DiscoveryClientRouteDefinitionLocator.DelegatingServiceInstance hints
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
Labels: bug

#2849 Fix registration of hints for Configurables conditional on classes.
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/ConfigurableHintsRegistrationProcessor.java
Labels: bug
