Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2024-03, with the labels that each got.

#3207 Declare Bean for the new public KeyValueConverter
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayAutoConfiguration.java
Labels: bug

#3274 Optimize for lazy loading of beans only once
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/handler/ProxyExchangeHandlerFunction.java
Labels: task

#3249 fix: combine the form map and queryParams to pass to RequestWrapper
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/FormFilter.java
Labels: in progress

#3218 RouterFunctionHolder not accessible. Fixes 3199
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/config/GatewayMvcPropertiesBeanDefinitionRegistrar.java
Labels: in progress

#3208 Update gateway-request-predicates.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/gateway-request-predicates.adoc
Labels: documentation

#3223 Fix documentation sample imports and missing .build() call
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/java-routes-api.adoc
Labels: documentation

#3224 Fix publishEvent RefreshRoutesResultEvent before cache.put
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/route/CachingRouteLocator.java
Labels: bug

#3187 Add missing colon
  docs/modules/ROOT/pages/spring-cloud-gateway/cors-configuration.adoc
Labels: documentation

#3186 Changed the constant name representing the default Time-to-Live (TTL)…
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/cache/LocalResponseCacheProperties.java
Labels: bug

#3150 fix typos in AddResponseHeaderGatewayFilterFactoryTests
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/factory/AddResponseHeaderGatewayFilterFactoryTests.java
Labels: task

#3136 Update dashboard to Grafana 9.x
  docs/modules/ROOT/assets/images/gateway-grafana-dashboard.jpeg
  docs/src/main/asciidoc/gateway-grafana-dashboard.json
  docs/src/main/asciidoc/images/gateway-grafana-dashboard.jpeg
Labels: enhancement

#3132 Improve error message
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/AbstractSslConfigurer.java
Labels: task

#3134 Allow forcing order of filters through Java DSL configuration.
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpec.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/route/builder/GatewayFilterSpecTests.java
Labels: enhancement

#3006 Adding Logging Statement to gRPC Server Shutdown
  spring-cloud-gateway-integration-tests/grpc/src/main/java/org/springframework/cloud/gateway/tests/grpc/GRPCApplication.java
Labels: task

#3010 RoutePredicateHandlerMapping can be optimized
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/handler/RoutePredicateHandlerMapping.java
Labels: task

#2997 To fix GH-2304 SaveSessionGatewayFilterFactory didn't work correctly
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/SaveSessionGatewayFilterFactory.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/factory/SaveSessionGatewayFilterFactoryTests.java
Labels: bug

#2993 Add a new method that returns a Mono<HttpClient>.
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyRoutingFilter.java
Labels: enhancement

#2977 Remove concatMap in lookupRoute to improve throughput
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/handler/RoutePredicateHandlerMapping.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/handler/RoutePredicateHandlerMappingTests.java
Labels: enhancement

#2934 Fixes gh-2933 GatewayFilter support @Order annotation
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/handler/FilteringWebHandler.java
Labels: enhancement

#2900 Fix ThrottleGatewayFilter in sample app to create TokenBucket only once
  spring-cloud-gateway-sample/src/main/java/org/springframework/cloud/gateway/sample/ThrottleGatewayFilter.java
Labels: task

#2805 Add @Order support for GlobalFilter
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/handler/FilteringWebHandler.java
Labels: enhancement

#2721 [#2720]Improve ReactiveLoadBalancerClientFilter implementation so tha…
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/ReactiveLoadBalancerClientFilter.java
Labels: enhancement

#2649 Fix for ModifyResponseBodyGatewayFilter not setting up response content-type
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/rewrite/ModifyResponseBodyGatewayFilterFactory.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/factory/rewrite/ModifyResponseBodyGatewayFilterFactoryTests.java
Labels: bug

#3300 make strategy key public
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/DedupeResponseHeaderGatewayFilterFactory.java
Labels: in progress

#3306 Update to spring-doc-actions v0.0.15
  .github/workflows/deploy-docs.yml
Labels: waiting-for-triage

#3193 Enhance AOT-Support (Issue#3171)
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/GatewayServerMvcAutoConfiguration.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/config/GatewayMvcAotRuntimeHintsRegistrar.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/config/GatewayMvcPropertiesBeanDefinitionRegistrar.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/config/RouterFunctionHolderFactory.java
Labels: in progress

#3314 Added removal of Connection option headers. Fixes GH-2653
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/headers/RemoveHopByHopHeadersFilter.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/headers/RemoveHopByHopHeadersFilterTests.java
Labels: in progress
