Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2024-09, with the labels that each got.

#3528 Remove GatewayReactiveOAuth2AutoConfiguration
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/GatewayReactiveOAuth2AutoConfiguration.java
  spring-cloud-gateway-server/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/config/GatewayAutoConfigurationTests.java
Labels: waiting-for-triage

#3502 In RedisRateLimiter，when an error occurs in executing a Lua script, the log is printed as eror
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiter.java
Labels: task

#3014 add QPS, Latency etc metrics to grafana template
  docs/src/main/asciidoc/gateway-grafana-dashboard.json
Labels: enhancement

#3409 Bump junit-pioneer from 1.9.1 to 2.2.0
  pom.xml
Labels: dependencies

#3534 Add a note about retry filter behavior in documentation
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/retry.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway/gatewayfilter-factories/retry-factory.adoc
Labels: documentation

#3019 add alarm template for spring cloud gateway
  docs/modules/ROOT/pages/spring-cloud-gateway/global-filters.adoc
  docs/src/main/asciidoc/gateway-alarming.adoc
Labels: documentation

#2517 [gh-2288] Fix for redis rate limiter not working with multiple routes
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiter.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/ratelimit/RedisRateLimiterTests.java
Labels: enhancement
