Repository spring-cloud/spring-cloud-gateway, pull requests merged in 2025-03, with the labels that each got.

#3709 importing RequestPredicate from reactive changed to servlet
  docs/modules/ROOT/pages/spring-cloud-gateway-server-webmvc/writing-custom-predicates-and-filters.adoc
Labels: documentation

#3701 Adding fix in java-based implementation of addRequestHeader for SCG server mvc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-webmvc/filters/addrequestheader.adoc
Labels: documentation

#3693 performance enhancement for request rate limiter lua script.
  spring-cloud-gateway-server/src/main/resources/META-INF/scripts/request_rate_limiter.lua
Labels: enhancement

#3627 small grammatical issue
  docs/modules/ROOT/pages/spring-cloud-gateway-server-webmvc/how-it-works.adoc
Labels: documentation

#3625 Updates to instanceof with variable
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/handler/FilteringWebHandler.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/route/RouteDefinitionRouteLocator.java
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/route/RouteRefreshListener.java
  spring-cloud-gateway-webflux/src/main/java/org/springframework/cloud/gateway/webflux/config/ProxyExchangeArgumentResolver.java
Labels: task

#3719 Fix Developer Guide Bug
  docs/modules/ROOT/pages/spring-cloud-gateway-server-webflux/developer-guide.adoc
Labels: documentation

#3724 Add enum values to JavaDocs to show in docs
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/HttpClientProperties.java
Labels: documentation

#3725 Add enum values to JavaDocs to show in docs
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/config/HttpClientProperties.java
Labels: documentation

#3658 Prevent duplicated encoding of `setPath()`, `stripPrefix()` in mvc
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctions.java
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctionsTests.java
Labels: bug

#3611 Suggests to dispose connection when cancelled In NettyWriteResponseFilter
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/NettyWriteResponseFilter.java
Labels: bug

#3713 RetryGatewayFilterFactory RetryConfig support Jitter & Timeout
  docs/modules/ROOT/pages/spring-cloud-gateway/gatewayfilter-factories/retry-factory.adoc
  spring-cloud-gateway-server/src/main/java/org/springframework/cloud/gateway/filter/factory/RetryGatewayFilterFactory.java
  spring-cloud-gateway-server/src/test/java/org/springframework/cloud/gateway/filter/factory/RetryGatewayFilterFactoryIntegrationTests.java
Labels: enhancement

#3483 Use getPath instead of getRawPath to prevent doulbe encoding of the URI
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctions.java
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctionsTests.java
Labels: in progress

#3747 Fixes routing issue with path filters and static uri
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/addrequestheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/addrequestheadersifnotpresent.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/addrequestparameter.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/addresponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/circuitbreaker-filter.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/deduperesponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/fallback-headers.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/maprequestheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/modifyrequestbody.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/modifyresponsebody.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/prefixpath.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/preservehostheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/ratelimiter.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/redirectto.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/removerequestheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/removerequestparameter.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/removeresponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/requestheadersize.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/requestsize.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/retry.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/rewritelocationresponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/rewritepath.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/rewriterequestparameter.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/rewriteresponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/setpath.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/setrequestheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/setrequesthostheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/setresponseheader.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/setstatus.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/stripprefix.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/filters/tokenrelay.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/gateway-request-predicates.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/java-routes-api.adoc
  docs/modules/ROOT/pages/spring-cloud-gateway-server-mvc/writing-custom-predicates-and-filters.adoc
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/config/RouterFunctionHolderFactory.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctions.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/FilterFunctions.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/LoadBalancerHandlerSupplier.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/filter/XForwardedRequestHeadersFilter.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/handler/DefaultHandlerSupplier.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/handler/HandlerDiscoverer.java
  spring-cloud-gateway-server-mvc/src/main/java/org/springframework/cloud/gateway/server/mvc/handler/HandlerFunctions.java
  spring-cloud-gateway-server-mvc/src/main/resources/META-INF/spring.factories
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/ServerMvcIntegrationTests.java
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/filter/BeforeFilterFunctionsTests.java
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/filter/StripPrefixStaticPortTests.java
  spring-cloud-gateway-server-mvc/src/test/java/org/springframework/cloud/gateway/server/mvc/test/HttpbinTestcontainers.java
  spring-cloud-gateway-server-mvc/src/test/resources/application-stripprefixstaticport.yml
Labels: in progress
